platform :osx, '10.7'
link_with 'GDJson', 'GDJsonTests'

# pod 'J2ObjC', :path => '~/dev/tools/lib/j2objc/J2ObjC.podspec'
pod 'J2ObjC', :git => 'https://github.com/goodow/j2objc.git', :commit => '5feab384f99531e435444de5a7d0f18ebb41dbe8'

pod 'GDJson', :path => '..'
# Next line needs to manually import generated sources to Xcode.
# podspec :path => '../GDJson.podspec'

#target :GDJsonTests, :exclusive => false do
#  platform :osx
#  pod 'GDJson', :path => '..'
#end
